name: Developer Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: squadmakers
          POSTGRES_PASSWORD: squadmakers
          POSTGRES_DB: squadmakers
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"
      - name: 'Run Tests'
        env:
          DATABASE_URL: postgresql://squadmakers:squadmakers@localhost:5432/squadmakers
          TEST_DATABASE_URL: postgresql://squadmakers:squadmakers@localhost:5432/squadmakers
          TEST: True
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python -m pytest --cov app
